[build]
  environment = { NPM_VERSION = "7.10.0", NODE_VERSION = "16.14.2", NETLIFY_USE_YARN = "true" }

[[redirects]]
  from = "/docs/agent"
  to = "/docs"

[[redirects]]
  from = "/docs/agent/collectors/collectors"
  to = "/docs/agent/collectors"
  
[[redirects]]
  from = "/docs/agent/cheatsheet"
  to = "/docs/cheatsheet"

[[redirects]]
  from = "/docs/agent/collectors/quickstart"
  to = "/docs/collect/enable-configure"

[[redirects]]
  from = "/docs/cloud/monitoring/alarms"
  to = "/docs/cloud/alerts-notifications/view-active-alerts"

[[redirects]]
  from = "/docs/cloud/monitor/alarms"
  to = "/docs/cloud/alerts-notifications/view-active-alerts" 

[[redirects]]
  from = "/docs/cloud/monitoring/*"
  to = "/docs/cloud/alerts-notifications/:splat"

[[redirects]]
  from = "/docs/agent/zh/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/zh/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/pt/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/pt/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/kr/docs/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/kr/*"
  to = "/docs/agent/:splat"
  status = 301

[[redirects]]
  from = "/docs/agent/health/tutorials/*"
  to = "/guides/monitor/:splat"

[[redirects]]
  from = "/docs/agent/guides/*"
  to = "/guides/:splat"

[[redirects]]
  from = "/docs/agent/tutorials/*"
  to = "/guides/:splat"

[[redirects]]
  from = "/docs/agent/step-by-step/*"
  to = "/guides/step-by-step/:splat"

[[redirects]]
  from = "/docs/agent/collectors/ebpf_process.plugin/"
  to = "/docs/agent/collectors/ebpf.plugin/"

[[redirects]]
  from = "/docs/agent/netdata-cloud/*"
  to = "/docs/cloud/"

[[redirects]]
  from = "dbengine-calc"
  to = "/docs/store/change-metrics-storage#calculate-the-system-resources-ram-disk-space-needed-to-store-metrics"

[[redirects]]
  from = "/docs/agent/database/calculator"
  to = "/docs/store/change-metrics-storage#calculate-the-system-resources-ram-disk-space-needed-to-store-metrics"

[[redirects]]
  from = "/docs/export"
  to = "/docs/export/external-databases"

[[redirects]]
  from = "/docs/visualize/view-all-nodes"
  to = "/docs/visualize/overview-infrastructure"
  
[[redirects]]
  from = "/docs/cloud/organize"
  to = "/docs/cloud/spaces"

[[redirects]]
  from = "/docs/agent/code-of-conduct"
  to = "/contribute/code-of-conduct"

[[redirects]]
  from = "/docs/agent/contributing"
  to = "/contribute/handbook"

[[redirects]]
  from = "/docs/agent/contributing/contributing-documentation"
  to = "/contribute/documentation"

[[redirects]]
  from = "/docs/agent/contributing/style-guide"
  to = "/contribute/style-guide"

[[redirects]]
  from = "/docs/agent/code_of_conduct"
  to = "/contribute/code-of-conduct"

[[redirects]]
  from = "/docs/agent/contributors"
  to = "/contribute/license"

[[redirects]]
  from = "/docs/agent/performance"
  to = "/guides/configure/performance"

[[redirects]]
  from = "/docs/agent/high-performance-netdata"
  to = "/guides/configure/performance"

[[redirects]]
  from = "/docs/cloud/collaborate/invite-your-team"
  to = "/docs/cloud/manage/invite-your-team"

[[redirects]]
  from = "/docs/configure/spaces-war-rooms"
  to = "/docs/quickstart/infrastructure"

[[redirects]]
  from = "/docs/configure/invite-collaborate"
  to = "/docs/quickstart/infrastructure"

[[redirects]]
  from = "/docs/agent/configuration-guide"
  to = "/docs/configure/common-changes"

[[redirects]]
  from = "/docs/cloud/faq-glossary"
  to = "https://community.netdata.cloud/docs"

  [[redirects]]
  from = "/docs/cloud/faq"
  to = "https://community.netdata.cloud/docs"

[[redirects]]
  from = "/docs/agent/export"
  to = "/docs/export/external-databases"

[[redirects]]
  from = "/docs/get"
  to = "/docs/get-started"

[[redirects]]
  from = "/docs/agent/get"
  to = "/docs/get-started"

[[redirects]]
  from = "/docs/agent/getting-started"
  to = "/docs/get-started"

[[redirects]]
  from = "/docs/agent/packaging/DISTRIBUTIONS"
  to = "/docs/agent/packaging/PLATFORM_SUPPORT"

[[redirects]]
  from = "/docs/agent/packaging/installer/methods/alpine"
  to = "/docs/agent/packaging/installer/methods/kickstart"

[[redirects]]
  from = "/docs/agent/packaging/installer/methods/kickstart-64"
  to = "/docs/agent/packaging/installer/methods/kickstart#static-builds"

[[redirects]]
from = "/docs/agent/packaging/installer/methods/packages"
to = "/docs/agent/packaging/installer/methods/kickstart#native-packages"

# redirects for collectors migrated from Python to Go

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/apache"
to = "/docs/agent/collectors/go.d.plugin/modules/apache"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/chrony"
to = "/docs/agent/collectors/go.d.plugin/modules/chrony"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/couchdb"
to = "/docs/agent/collectors/go.d.plugin/modules/couchdb"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/dns_query_time"
to = "/docs/agent/collectors/go.d.plugin/modules/dnsquery"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/dnsdist"
to = "/docs/agent/collectors/go.d.plugin/modules/dnsdist"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/elasticsearch"
to = "/docs/agent/collectors/go.d.plugin/modules/elasticsearch"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/energid"
to = "/docs/agent/collectors/go.d.plugin/modules/energid"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/freeradius"
to = "/docs/agent/collectors/go.d.plugin/modules/freeradius"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/httpcheck"
to = "/docs/agent/collectors/go.d.plugin/modules/httpcheck"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/isc_dhcpd"
to = "/docs/agent/collectors/go.d.plugin/modules/isc_dhcpd"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/mysql"
to = "/docs/agent/collectors/go.d.plugin/modules/mysql"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/nginx"
to = "/docs/agent/collectors/go.d.plugin/modules/nginx"

#[[redirects]]
#from = "/docs/agent/collectors/python.d.plugin/ovpn_status_log"
#to = "/docs/agent/collectors/go.d.plugin/modules/ovpn_status_log"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/phpfpm"
to = "/docs/agent/collectors/go.d.plugin/modules/phpfpm"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/portcheck"
to = "/docs/agent/collectors/go.d.plugin/modules/portcheck"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/postgres"
to = "/docs/agent/collectors/go.d.plugin/modules/postgres"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/powerdns"
to = "/docs/agent/collectors/go.d.plugin/modules/powerdns"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/redis"
to = "/docs/agent/collectors/go.d.plugin/modules/redis"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/web_log"
to = "/docs/agent/collectors/go.d.plugin/modules/weblog"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/rabbitmq"
to = "/docs/agent/collectors/go.d.plugin/modules/rabbitmq"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/ntpd"
to = "/docs/agent/collectors/go.d.plugin/modules/ntpd"

[[redirects]]
from = "/docs/agent/collectors/python.d.plugin/proxysql"
to = "/docs/agent/collectors/go.d.plugin/modules/proxysql"

# redirects for collectors migrated from Node to Go

[[redirects]]
from = "/docs/agent/collectors/node.d.plugin/snmp"
to = "/docs/agent/collectors/go.d.plugin/modules/snmp"

# Deprecated backends

[[redirects]]
from = "/docs/agent/backends/prometheus"
to = "/docs/agent/exporting/prometheus"

# Reorganizing new docs 02/25/2023

[[redirects]]
from = "/docs/nightly/concepts/events-feed"
to = "/docs/nightly/troubleshooting-and-machine-learning/events-feed"

[[redirects]]
from = "/docs/nightly/concepts/netdata-functions"
to = "/docs/nightly/troubleshooting-and-machine-learning/functions"

[[redirects]]
from = "/docs/nightly/concepts/role-based-access-model"
to = "/docs/nightly/deployment-in-production/security/role-based-access-model"

[[redirects]]
from = "/docs/nightly/operations/alerts/add-discord-notification-configuration"
to = "/docs/nightly/alerts-and-notifications/cloud-alert-notifications/add-discord-notification-configuration"

[[redirects]]
from = "/docs/nightly/operations/alerts/add-webhook-notification-configuration"
to = "/docs/nightly/alerts-and-notifications/cloud-alert-notifications/add-webhook-notification-configuration"

[[redirects]]
from = "/docs/nightly/operations/alerts/add-pagerduty-notification-configuration"
to = "/docs/nightly/alerts-and-notifications/cloud-alert-notifications/add-pagerduty-notification-configuration"

[[redirects]]
from = "/docs/nightly/operations/alerts/add-slack-notification-configuration"
to = "/docs/nightly/alerts-and-notifications/cloud-alert-notifications/add-slack-notification-configuration"


