name: Test external links
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 18 * * *'
env:
  WEBSITE_URL: "https://learn.netdata.cloud/"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run BLC on internal links
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude-internal --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36'

#    - uses: actions/checkout@v2
#      if: failure()
#
#    - uses: JasonEtco/create-an-issue@v2
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        LINK_TYPE: external
#      with:
#        filename: ${{ env.ISSUE_TEMPLATE }}
#      if: failure()
